name = "PellsEquation"
uuid = "b53f056f-43f6-4734-8d94-3aedffe6e4fb"
authors = ["Bryan Hill <bf361640-7eb8-4e29-80f7-5250fa6b442b@aleeas.com> and contributors"]
version = "0.2.2"

[deps]
ModularSquareRoots = "544cf62c-00ce-4949-a641-e1b79df66db1"
Primes = "27ebfcd6-29c5-5fa9-bf4b-fb8fc14df3ae"

[compat]
ModularSquareRoots = "0.1.3"
Primes = "0.5.6"
julia = "1.8"
